name: Test StarDist and Cellpose

on:
  push:
    branches: [ master ]
    paths-ignore:
      - .github/workflows/macos_test.yaml
      - .github/workflows/integration_test.yaml
  pull_request:
    branches: [ master ]

env:
  SCRIPT_PATH_1C: .github/scripts/stardist2d_1c.py
  SCRIPT_PATH_3C: .github/scripts/stardist2d_3c.py
  CP_SCRIPT_PATH_1C: .github/scripts/cellpose_1c.py
  CP_SCRIPT_PATH_3C: .github/scripts/cellpose_3c.py

jobs:
  integration-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            os: ubuntu-latest
            url_file_name: fiji-stable-linux64-jdk.zip
            fiji_executable: ImageJ-linux64
          - name: windows
            os: windows-latest
            url_file_name: fiji-stable-win64-jdk.zip
            fiji_executable: ImageJ-win64.exe
          - name: macos-arm64-14
            os: macos-14
            url_file_name: fiji-stable-macosx-jdk.zip
            fiji_executable: Contents/MacOS/ImageJ-macosx
          - name: macos-arm64-15
            os: macos-15
            url_file_name: fiji-stable-macosx-jdk.zip
            fiji_executable: Contents/MacOS/ImageJ-macosx
          - name: macos-x86_64
            os: macos-13
            url_file_name: fiji-stable-macosx-jdk.zip
            fiji_executable: Contents/MacOS/ImageJ-macosx
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Set up Fiji
        shell: bash
        run: |
          mkdir -p fiji
          curl -L -o fiji.zip https://downloads.imagej.net/fiji/stable/${{ matrix.url_file_name }}
          unzip fiji.zip -d fiji

      - name: Install deepimageJ
        shell: bash
        run: |
          fiji/Fiji.app/${{ matrix.fiji_executable }} --headless --update add-update-site "DeepImageJ" "https://sites.imagej.net/DeepImageJ/"
          fiji/Fiji.app/${{ matrix.fiji_executable }} --headless --update update

      - name: rm deepimagej file
        shell: bash
        run: |
          rm -f /fiji/Fiji.app/plugins/deepimagej-*.jar

      - name: Build Plugin
        shell: bash
        run: mvn clean package

      - name: Get plugin name and version
        shell: bash
        run: |
          MVN_VERSION=$(mvn -q \
            -Dexec.executable=echo \
            -Dexec.args='${project.version}' \
            --non-recursive \
            exec:exec)
          MVN_NAME=$(mvn -q \
            -Dexec.executable=echo \
            -Dexec.args='${project.artifactId}' \
            --non-recursive \
            exec:exec)
          echo "version=${MVN_VERSION}" >> $GITHUB_OUTPUT
          echo "name=${MVN_NAME}" >> $GITHUB_OUTPUT
        id: mvn_info

      - name: Copy Plugin to Fiji
        shell: bash
        run: cp target/${{steps.mvn_info.outputs.name}}-${{steps.mvn_info.outputs.version}}.jar fiji/Fiji.app/plugins/

      - name: Download and test StarDist 2d 1 channel
        shell: bash
        run: |
          fiji/Fiji.app/${{ matrix.fiji_executable }} --headless --console  ${{ env.SCRIPT_PATH_1C }}

      - name: Download and test StarDist 2d 3 channes
        shell: bash
        run: |
          fiji/Fiji.app/${{ matrix.fiji_executable }} --headless --console  ${{ env.SCRIPT_PATH_3C }}

      - name: Download and test Cellpose 2d 1 channel
        shell: bash
        run: |
          fiji/Fiji.app/${{ matrix.fiji_executable }} --headless --console  ${{ env.CP_SCRIPT_PATH_1C }}

      - name: Download and test Cellpose 2d 3 channes
        shell: bash
        run: |
          fiji/Fiji.app/${{ matrix.fiji_executable }} --headless --console  ${{ env.CP_SCRIPT_PATH_3C }}
